# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ML-CLAS
                                 A QGIS plugin
 This plugin can be used to apply classification on agricultural fields
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-04
        copyright            : (C) 2023 by Uday Kiran Jayanthi
        email                : udaykiranjayanthi099@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Classification class from file Classification.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .classification import Classification
    return Classification(iface)
