# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ML-CLAS
                                 A QGIS plugin
 This plugin can be used to apply classification on agricultural fields
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-03-04
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Sravani Duvvuri
        email                : sravanidvr@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog 

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .classification_dialog import ClassificationDialog, HelpDialog, TWDTWHelpDialog
import os

import processing 
from qgis.core import QgsRasterLayer, QgsVectorLayer, QgsProject, QgsVectorFileWriter
from osgeo import gdal, ogr

class Classification:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ML-CLAS_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&ML-CLAS')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ML-CLAS', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/classification/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'ML-CLAS'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&ML-CLAS'),
                action)
            self.iface.removeToolBarIcon(action)

    def select_input_rasters(self):
        filenames, _filter = QFileDialog.getOpenFileNames(self.dlg, "Select input raster files ","", '*.*')
        self.dlg.leInputRaster.setText(';'.join(filenames))
        ### definition and calling function of set_coordinates() for these files
        if filenames:
            self.set_coordinates(filenames[0])

    def set_coordinates(self,file):
        lyr = QgsRasterLayer(file)
        self.dlg.leMinX.setText(str(lyr.extent().xMinimum()))
        self.dlg.leMinY.setText(str(lyr.extent().yMinimum()))
        self.dlg.leMaxX.setText(str(lyr.extent().xMaximum()))
        self.dlg.leMaxY.setText(str(lyr.extent().yMaximum()))
        ###

    def select_input_vector(self):
        filename, _filter = QFileDialog.getOpenFileName(self.dlg, "Select input vector file ","", '*.*')
        self.dlg.leInputVector.setText(filename)

    def select_train_points(self):
        filename, _filter = QFileDialog.getOpenFileName(self.dlg, "Select training points file ","", '*.*')
        self.dlg.lePoints.setText(filename)

    def select_output_folder(self):
        flags = QFileDialog.ShowDirsOnly
        dirpath = str(QFileDialog.getExistingDirectory(self.dlg, 'Choose a output folder', '', flags))
        self.dlg.leOutput.setText(dirpath)

    def select_input_rasters_twdtw(self):
        filenames, _filter = QFileDialog.getOpenFileNames(self.dlg, "Select input raster files ","", '*.*')
        self.dlg.leInputRaster_twdtw.setText(';'.join(filenames))

        ### calling function set_coordinates for TWDTW 
        if filenames:
            self.set_coordinates(filenames[0])

    def select_input_vector_twdtw(self):
        filename, _filter = QFileDialog.getOpenFileName(self.dlg, "Select input vector file ","", '*.*')
        self.dlg.leInputVector_twdtw.setText(filename)

    def select_timeline_twdtw(self):
        filename, _filter = QFileDialog.getOpenFileName(self.dlg, "Select timeline file ","", '*.*')
        self.dlg.leTimeline_twdtw.setText(filename)

    def select_sample_projection_twdtw(self):
        filename, _filter = QFileDialog.getOpenFileName(self.dlg, "Select sample projection file ","", '*.*')
        self.dlg.leSP_twdtw.setText(filename)

    def select_field_samples_twdtw(self):
        filename, _filter = QFileDialog.getOpenFileName(self.dlg, "Select field samples file ","", '*.*')
        self.dlg.leFieldSamples_twdtw.setText(filename)

    def select_output_folder_twdtw(self):
        flags = QFileDialog.ShowDirsOnly
        dirpath = str(QFileDialog.getExistingDirectory(self.dlg, 'Choose a output folder', '', flags))
        self.dlg.leOutput_twdtw.setText(dirpath)

    def openHelpTab(self):
        self.sc = HelpDialog()
        self.sc.show()

    def openTWDTWHelpTab(self):
        self.sc = TWDTWHelpDialog()
        self.sc.show()

    def getAccuracy(self, output_matrix):
        total = 0
        totalTrue = 0

        confusion_matrix = open(output_matrix, "r")

        for i, line in enumerate(confusion_matrix):
            if(i==0):
                continue
            
            row = line.split(",")
            row = [int(i) for i in row]
            total += sum(row)
            totalTrue += row[i-1]

        accuracy = totalTrue/total * 100
        return accuracy

    def copyVectorFile(self, input_vector, output_vector):
        vector_layer = QgsVectorLayer(input_vector, "vector_layer", "ogr")

        # Create a new writer for the output vector file
        writer = QgsVectorFileWriter(output_vector, "UTF-8", vector_layer.fields(), vector_layer.wkbType(), vector_layer.crs(), "ESRI Shapefile")

        # Check if the writer was successfully initialized
        if writer.hasError() != QgsVectorFileWriter.NoError:
            print("Error creating output vector file:", writer.errorMessage())
            return "error"

        # Copy features from the input vector layer to the writer
        for feature in vector_layer.getFeatures():
            writer.addFeature(feature)

        # Commit changes to the output vector file
        del writer
        return "success"

    def preProcessRaster(self, input_rasters, input_vector, output_folder, processed_raster_output, skip_nodata_value = False):

        rasters_output_folder = output_folder + "/rasters"
        os.mkdir(rasters_output_folder)

        processed_rasters = [];

        for (index, input_raster) in enumerate(sorted(input_rasters.split(";"))):
            print("RASTER LAYER -", index+1)

            # Create a new vector file path for each iteration
            vector_copy = rasters_output_folder + "/copy_" + str(index+1) + ".shp"

            # Copy the vector file to create a new copy
            result = self.copyVectorFile(input_vector, vector_copy)

            if(result == "error"):
                continue

            # Add mean attribute to vector, calculate using zonal statistics of raster fields

            zonal_parameters = {
                'INPUT_RASTER': input_raster,
                'RASTER_BAND': 1,
                'INPUT_VECTOR': vector_copy,
                'COLUMN_PREFIX': "_",
                'STATS': 2, # for mean
            }
            print("zonal statistics")
            processing.run("qgis:zonalstatistics", zonal_parameters)

            # Rasterize (vector to raster), mean as raster pixel value

            inputRaster = QgsRasterLayer(input_raster)
            pixelSizeX= inputRaster.rasterUnitsPerPixelX()
            pixelSizeY = inputRaster.rasterUnitsPerPixelY()
            rasterized_output = rasters_output_folder + "/processed_" + input_raster.split("/")[-1]

            rasterize_parameters = {
                'INPUT': vector_copy,
                'FIELD': "_mean",
                'BURN': 0,
                'UNITS': 1, # 0: Pixels, 1: Georeferenced units
                'WIDTH': pixelSizeX,
                'HEIGHT': pixelSizeY,
                'EXTENT': vector_copy,
                'NODATA': 0,
                'OUTPUT': rasterized_output,
            }
            print("rasterize")
            processing.run("gdal:rasterize", rasterize_parameters)

            processed_rasters.append(rasterized_output)
        
        merge_parameters = {
            "INPUT": processed_rasters,
            "SEPARATE": False,
            "NODATA_INPUT": 0,
            "NODATA_OUTPUT": 0,
            "OUTPUT": processed_raster_output,
        }
        merge_parameters_skip_nodata = {
            "INPUT": processed_rasters,
            "SEPARATE": True,
            "OUTPUT": processed_raster_output
        }
        print("merge rasters")
        processing.run("gdal:merge", merge_parameters_skip_nodata if skip_nodata_value else merge_parameters )
        
        return processed_raster_output

    def extractAndJoinByLocation(self, input_vector, points, output_vector):
        
        # extract features in input vector which interset with the location points
        extract_parameters = {
            'INPUT': input_vector,
            'PREDICATE': [0],
            'INTERSECT': points,
            'OUTPUT': 'memory:',
            'DATA_TYPE': 'IGNORE_INVALID',
        }
        print("Extract by location")
        extracted = processing.run("native:extractbylocation", extract_parameters)

        # join attributes of intersecting points with features 
        join_parameters = {
            'INPUT': extracted['OUTPUT'],
            'JOIN': points,
            'PREDICATE': [0],
            'METHOD': 1,
            'DISCARD_NONMATCHING': True,
            'OUTPUT': output_vector,
        }
        print("Join by location")
        joined = processing.run("qgis:joinattributesbylocation", join_parameters)

        return joined['OUTPUT']

    def addUniqueClass(self, input_vector, input_field, output_field, class_summary_output, output_vector):

        uniqueindex_parameters = {
            'INPUT': input_vector,
            'FIELD': input_field,
            'FIELD_NAME': output_field,
            'OUTPUT': output_vector,
            'SUMMARY_OUTPUT': class_summary_output,
        }
        print("Add unique value index field")
        uniqueIndexResult = processing.run("native:adduniquevalueindexfield", uniqueindex_parameters)

        return uniqueIndexResult['OUTPUT'], uniqueIndexResult['SUMMARY_OUTPUT']

    def addUniqueClassManual(self, input_layer, input_field, output_field):

        # open shapefile
        # shapefile_path = "path/to/shapefile.shp"
        ds = ogr.Open(input_layer, 1)

        # get layer and fields
        layer = ds.GetLayer()
        layer_defn = layer.GetLayerDefn()

        # add new field to layer
        new_field = ogr.FieldDefn(output_field, ogr.OFTInteger)
        layer.CreateField(new_field)

        # create a dictionary to store unique values of label field
        unique_labels = {}

        # iterate over features and assign index values to each unique label
        for feature in layer:
            label_value = feature.GetField(input_field)
            if label_value not in unique_labels:
                unique_labels[label_value] = len(unique_labels) + 1
            feature.SetField(output_field, unique_labels[label_value])
            layer.SetFeature(feature)

        # close shapefile
        ds = None
        return unique_labels

    def computeFromConfusionMatrix(self, output_matrix, traning_report):
        total = 0
        totalTrue = 0

        data = open(output_matrix, "r")
        confusion_matrix = []
        classWiseData = []
        sumOfRowColumnProducts = 0

        for i, line in enumerate(data):
            if(i==0):
                continue
            
            row = line.split(",")
            row = [int(j) for j in row]
            confusion_matrix.append(row)

            total += sum(row)
            totalTrue += row[i-1]


        # Columns=prediction,Rows=reference.
        for i in range(len(confusion_matrix)):

            row = confusion_matrix[i]
            column = [r[i] for r in confusion_matrix]

            rowSum = sum(row)
            columnSum = sum(column)

            sumOfRowColumnProducts += rowSum * columnSum

            classData = {}
            # TP
            classData["TP"] = row[i]
            # FP
            classData["FN"] = rowSum - classData["TP"]
            # FN
            classData["FP"] = columnSum - classData["TP"]
            # TN
            classData["TN"] = total - (classData["FP"] + classData["FN"] + classData["TP"])

            # precision
            classData["precision"] = classData["TP"]/(classData["TP"]+classData["FP"])
            # recall
            classData["recall"] = classData["TP"]/(classData["TP"]+classData["FN"])
            # f1score
            classData["f1-score"] = 2*classData["TP"]/(2*classData["TP"]+classData["FP"]+classData["FN"])


            # print(classData["precision"],classData["recall"],classData["f1-score"])
            classWiseData.append(classData)

        overall_accuracy = totalTrue/total * 100
        kappa = ((totalTrue*total)-sumOfRowColumnProducts)/(pow(total,2) - sumOfRowColumnProducts)
        
        lines = []

        header = "{:<20}".format("") + "\t".join(["{:>9}".format("Class"+str(i+1)) for i in range(len(classWiseData))])

        lines.append(header)

        for prop in ["precision", "recall", "f1-score"]:
            row = "{:<20}".format(prop) + "\t".join(["{:>9.2f}".format(classData[prop]) for classData in classWiseData])
            lines.append(row)

        lines.append("\n\n")
        lines.append("{:<20}".format("overall accuracy")+"{:>9.2f}".format(overall_accuracy))
        lines.append("{:<20}".format("kapppa")+"{:>9.2f}".format(kappa))
        
        file = open(traning_report, "a");
        file.writelines([line+"\n" for line in lines])
        file.close()

    def classify_dzetsaka(self):

        print("classification RF_SVM initiated")
        input_rasters = self.dlg.leInputRaster.text()
        input_vector = self.dlg.leInputVector.text()
        train_points = self.dlg.lePoints.text()
        output_folder = self.dlg.leOutput.text()
        split_percent = self.dlg.leSplit.text()
        label_field_name = self.dlg.leField.text()
        train_algorithm = self.dlg.cbAlgorithm.currentText()

        class_summary_output = output_folder + "/class_summary_output.dbf"
        processed_raster_output = output_folder + "/processed_raster_output.tif"
        training_vector = output_folder + "/training_vector.shp"

        class_field_name = "class"


        self.extractAndJoinByLocation(input_vector, train_points, training_vector)

        unique_labels = self.addUniqueClassManual(training_vector, label_field_name, class_field_name)
        print(unique_labels)

        self.preProcessRaster(input_rasters, input_vector, output_folder, processed_raster_output)

        # train the model (save the model and print accuracy)

        output_model = output_folder + "/output_model.txt"
        output_matrix = output_folder + "/output_matrix.txt"

        train_parameters = {
            'INPUT_RASTER': processed_raster_output,
            'INPUT_LAYER': training_vector,
            'INPUT_COLUMN': class_field_name,
            'SPLIT_PERCENT': split_percent, #test percent
            'TRAIN': self.dzetsaka_algorithms[train_algorithm], 
            'OUTPUT_MODEL': output_model,
            'OUTPUT_MATRIX': output_matrix,
            'PARAMGRID': "",
        }
        print("Training model..")
        processing.run("dzetsaka:Train algorithm", train_parameters)

        traning_report = output_folder + "/traning_report.txt"
        
        self.computeFromConfusionMatrix(output_matrix, traning_report)
        print("Traning report generated.")

        # classify the total fields

        output_raster = output_folder + "/output_raster.tif"
        confidence_raster = output_folder + "/confidence_raster.tif"

        classification_parameters = {
            'INPUT_RASTER': processed_raster_output,
            'INPUT_MODEL': output_model,
            'OUTPUT_RASTER': output_raster,
            'CONFIDENCE_RASTER': confidence_raster,
        }
        print("Classifying...")
        processing.run("dzetsaka:Predict model (classification map)", classification_parameters)

        print("Classification completed, checkout ", output_raster)

    def classify_twdtw(self):

        print("classification TWDTW initiated")
        input_rasters = self.dlg.leInputRaster_twdtw.text()
        input_vector = self.dlg.leInputVector_twdtw.text()
        output_folder = self.dlg.leOutput_twdtw.text()

        timeline = self.dlg.leTimeline_twdtw.text()
        sample_prjection = self.dlg.leSP_twdtw.text()
        field_samples = self.dlg.leFieldSamples_twdtw.text()
        split_percent = self.dlg.leSplit_twdtw.text()

        stacked_raster_output = output_folder + "/stacked_raster_output.tif"

        self.preProcessRaster(input_rasters, input_vector, output_folder, stacked_raster_output, skip_nodata_value = True)

        twdtw_parameters = {
            'INPUT_RASTER': stacked_raster_output,
            'TIMELINE': timeline,
            'FIELD_SAMPLES': field_samples,
            'SAMPLE_PROJECTION': sample_prjection,
            'SPLIT': float(split_percent)/100,
            'OUTPUT_FOLDER': output_folder,
        }
        print("TWDTW started..")
        processing.run("r:twdtw_classification", twdtw_parameters)

        print("TWDTW Completed.")

    ### Qcombo algorithm selection drop down.
    def on_algorithm_changed(self,text):
        """Handle algorithm selection changes"""
        if text in ["Support Vector Machine", "Random-Forest"]:
            self.dlg.stackedWidget.setCurrentIndex(0)
        elif text == "TWDTW":
            self.dlg.stackedWidget.setCurrentIndex(1)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        self.dzetsaka_algorithms = {
            "Gaussian Mixture Model": 0,
            "Random-Forest": 1,
            "K-Nearest Neighbors": 2,
            "Support Vector Machine": 3,
        }

        if self.first_start == True:
            self.first_start = False
            self.dlg = ClassificationDialog()
            self.dlg.cbAlgorithm.addItems(["Support Vector Machine", "Random-Forest","TWDTW"])   ## Added TWDTW as selection algorithm 
            self.dlg.cbAlgorithm.currentTextChanged.connect(self.on_algorithm_changed)
            # DZETSAKA Inputs
            
            self.dlg.pbInputRaster.clicked.connect(self.select_input_rasters)   
            self.dlg.pbInputVector.clicked.connect(self.select_input_vector)
            self.dlg.pbPoints.clicked.connect(self.select_train_points)
            self.dlg.pbOutput.clicked.connect(self.select_output_folder)

            #self.dlg.cbAlgorithm.addItems(["Support Vector Machine", "Random-Forest","TWDTW"])

            self.dlg.pbDzClassify.clicked.connect(self.classify_dzetsaka)
            self.dlg.helpButton.clicked.connect(self.openHelpTab)

            # TWDTW Inputs

            self.dlg.pbInputRaster_twdtw.clicked.connect(self.select_input_rasters_twdtw)   
            self.dlg.pbInputVector_twdtw.clicked.connect(self.select_input_vector_twdtw)
            self.dlg.pbTimeline_twdtw.clicked.connect(self.select_timeline_twdtw)
            self.dlg.pbSP_twdtw.clicked.connect(self.select_sample_projection_twdtw)
            self.dlg.pbFieldSamples_twdtw.clicked.connect(self.select_field_samples_twdtw)
            self.dlg.pbOutput_twdtw.clicked.connect(self.select_output_folder_twdtw)

            self.dlg.pbDzClassify_twdtw.clicked.connect(self.classify_twdtw)
            self.dlg.helpButton_twdtw.clicked.connect(self.openTWDTWHelpTab)

            #self.set_coordinates()
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            ### Added for coordinates box
            minx = float(self.dlg.leMinX.text())
            miny = float(self.dlg.leMinY.text())
            maxx = float(self.dlg.leMaxX.text())
            maxy = float(self.dlg.leMaxY.text())
