# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ClassificationDialog
                                 A QGIS plugin
 This plugin can be used to apply classification on agricultural fields
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-04
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Uday Kiran Jayanthi
        email                : udaykiranjayanthi099@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'classification_dialog_base.ui'))


class ClassificationDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(ClassificationDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)


HELP_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'help.ui'))

class HelpDialog(QtWidgets.QDialog, HELP_CLASS):
    def __init__(self, parent=None):
        super(HelpDialog, self).__init__(parent)
        self.setupUi(self)


TWDTW_HELP_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'twdtw_help.ui'))

class TWDTWHelpDialog(QtWidgets.QDialog, TWDTW_HELP_CLASS):
    def __init__(self, parent=None):
        super(TWDTWHelpDialog, self).__init__(parent)
        self.setupUi(self)
